const { parseBool, parseNumber, parseCsvList } = require('./config');
const { LIVE_STOCK_POLICY_DEFAULTS } = require('./live-stock-policy');
const { safeNumber } = require('./util');
const { parseSymbolList } = require('./volatile-stock-universe');

function shouldUseStricterLiveEntryDefaults(env = process.env) {
  const tradingMode = String(env.TRADING_MODE || '').trim().toLowerCase();
  const scannerMode = String(env.SCANNER_MODE || env.SCANNER_PROFILE || '').trim().toLowerCase();
  const liveTradingEnabled = parseBool(env.LIVE_TRADING_ENABLED, false);
  return tradingMode === 'live'
    || liveTradingEnabled === true
    || scannerMode === 'live-market'
    || scannerMode === 'live';
}

const SCANNER_CONFIG_KEYS = [
  'apiKeyId', 'apiSecretKey', 'baseUrl', 'twelveDataApiKey', 'twelveDataBaseUrl',
  'localBaseUrl', 'enabled', 'symbols', 'excludedBuySymbols',
  'intervalMs', 'maxCandidatesPerRun', 'notional', 'minBuyNotional', 'maxOpenPositions',
  'stopLossDollars', 'stopLossNotionalPct', 'stopLossMaxDollars',
  'trailingProfitStartDollars', 'trailingProfitGivebackDollars',
  'stalePositionExitEnabled', 'stalePositionMaxHoldMinutes',
  'stalePositionMinPeakProfitDollars', 'stalePositionMaxExitPnlDollars',
  'stalledWinnerExitEnabled', 'stalledWinnerMaxHoldMinutes',
  'stalledWinnerMaxMinutesSincePeak', 'stalledWinnerMinProfitDollars',
  'sellNetProfitFloorDollars',
  'requireMultiSourceConfirmation', 'allowContrarianEntries', 'blockBuys', 'sellMaxPriceDiffPct',
  'singleSourceMomentumEnabled', 'singleSourceMomentumMinRankScore',
  'minMovePct', 'requireRecentMomentum', 'minRecentMovePct', 'minRecentRangePct',
  'minRecentCloseLocationPct',
  'recentTradePenaltyMinutes', 'recentTradeRankPenalty',
  'recentLossPenaltyMinutes', 'recentLossRankPenalty',
  'recentStaleExitPenaltyMinutes', 'recentStaleExitRankPenalty',
  'recentStopExitPenaltyMinutes', 'recentStopExitRankPenalty',
  'antiChurnEnabled', 'antiChurnRetentionHours',
  'antiChurnCleanWinCooldownSeconds', 'antiChurnTrailingWinCooldownSeconds',
  'antiChurnSmallWinCooldownSeconds', 'antiChurnGoodLossCooldownSeconds',
  'antiChurnBadLossCooldownSeconds', 'antiChurnHardStopoutCooldownSeconds',
  'antiChurnRepeatedStopoutMultiplier', 'antiChurnMaxCooldownSeconds',
  'antiChurnRecentWinnerProtectionEnabled', 'antiChurnRecentWinnerWindowSeconds',
  'antiChurnTinyExitDollars', 'antiChurnRapidRoundTripSeconds',
  'antiChurnWindowSeconds', 'antiChurnGuardScoreThreshold',
  'antiChurnGuardTradeCount', 'antiChurnGuardStopoutCount',
  'antiChurnGuardTinyExitCount', 'antiChurnGuardRoundTripCount',
  'antiChurnGuardSymbolLoopCount', 'antiChurnGuardSetupLoopCount',
  'setupFatigueEnabled', 'setupFatigueThreshold', 'setupFatigueDecayPerHour',
  'setupFatigueStopoutPoints', 'setupFatigueBadLossPoints', 'setupFatigueGoodLossPoints',
  'setupFatigueCleanWinRecoveryPoints', 'setupFatiguePauseSeconds', 'setupFatigueMaxPauseSeconds',
  'sessionGuardsEnabled', 'stopoutClusterBlockMinutes', 'stopoutClusterBlockCount',
  'maxBuyRiskScore', 'spreadRankPenaltyThresholdPct', 'spreadRankPenaltyPerPct',
  'spreadRankPenaltyCap', 'minAdjustedRankScore', 'keepAlive',
  'runtimeStateEnabled', 'requireMarketOpen',
  'openingNoiseMinutes', 'nearCloseManageOnlyMinutes',
  'volatilityStopEnabled', 'marketQualityRankingEnabled',
  'executionQualityFeedbackEnabled', 'executionQualityRankPenaltyEnabled',
  'executionQualitySizeMultiplierEnabled', 'executionQualityCooldownEnabled',
  'maxExecutionQualityRankPenalty', 'minExecutionQualitySizeMultiplier',
  'highSlippageThresholdPct', 'badFillThresholdPct', 'executionQualityDecayPerHour',
  'riskBudgetSizingEnabled', 'maxRiskPerTradeDollars', 'maxRiskPerTradePctEquity',
  'maxTradeNotional', 'minStopDistanceDollars', 'maxStopDistanceDollars',
  'allowRiskBudgetFractionalShares', 'riskBudgetRequireBrokerEquity',
  'positionSizingMode', 'maxBuyingPowerDeploymentPct', 'buyingPowerCashReserve',
  'allowBuyingPowerFractionalShares',
  'candidateLifecycleEnabled', 'candidateMinScansBeforeEntry', 'candidateMinSecondsBeforeEntry',
  'candidateMaxAgeSeconds', 'candidateConfirmationRequired', 'candidateQueueMaxSize',
  'rankConfidenceDecayEnabled', 'rankConfidenceHalfLifeSeconds', 'rankConfidenceMaxStaleSeconds',
  'huntToMonitorLatchEnabled', 'monitorModeAllowsNewBuys', 'manageOnlyBlocksBuys',
  'microRotationGuardEnabled', 'rotationSoftBandPoints', 'rotationHardBandPoints',
  'rotationMinHoldScans',
  'hotSlotRotationEnabled', 'hotSlotRotationMinHeatScore', 'hotSlotRotationMinMarketScore',
  'rotationRequireBreakevenOrBetter', 'rotationAllowTinyLoss', 'rotationMaxAllowedLossDollars',
  'rotationProtectStrongRunners', 'rotationRecheckAfterExit', 'rotationExitTimeoutSeconds',
  'rotationEntryRecheckMaxAgeSeconds', 'scannerSymbolSource',
];

function buildScannerConfig(env = process.env) {
  const stricterLiveEntryDefaults = shouldUseStricterLiveEntryDefaults(env);
  return {
    apiKeyId: env.ALPACA_API_KEY_ID || '',
    apiSecretKey: env.ALPACA_API_SECRET_KEY || '',
    baseUrl: trimTrailingSlash(env.ALPACA_DATA_BASE_URL || 'https://data.alpaca.markets'),
    twelveDataApiKey: env.TWELVE_DATA_API_KEY || env.TWELVEDATA_API_KEY || '',
    twelveDataBaseUrl: trimTrailingSlash(env.TWELVE_DATA_BASE_URL || 'https://api.twelvedata.com'),
    localBaseUrl: trimTrailingSlash(env.STOCK_SCANNER_LOCAL_BASE_URL || env.LOCAL_BASE_URL || ''),
    enabled: true,
    symbols: parseSymbolList(env.STOCK_SCANNER_SYMBOLS, []),
    excludedBuySymbols: parseSymbolList(env.STOCK_SCANNER_EXCLUDED_BUY_SYMBOLS, []),
    intervalMs: Math.max(15_000, Number(env.STOCK_SCANNER_INTERVAL_SECONDS || 60) * 1000 || 60_000),
    maxCandidatesPerRun: Math.max(1, Number(env.STOCK_SCANNER_MAX_CANDIDATES ?? 2) || 2),
    notional: Math.max(1, Number(env.BUY_NOTIONAL_TARGET ?? 150) || 150),
    minBuyNotional: Math.max(1, Number(env.MIN_BUY_NOTIONAL ?? 25) || 25),
    maxOpenPositions: Math.max(1, Number(env.MAX_OPEN_POSITIONS ?? 2) || 2),
    stopLossDollars: Math.max(0.01, Number(env.POSITION_STOP_LOSS_DOLLARS ?? 1) || 1),
    stopLossNotionalPct: Math.max(0, safeNumber(env.POSITION_STOP_LOSS_NOTIONAL_PCT, 0.75)),
    stopLossMaxDollars: Math.max(1, safeNumber(env.POSITION_STOP_LOSS_MAX_DOLLARS, 2.5)),
    trailingProfitStartDollars: Math.max(0.01, Number(env.TRAILING_PROFIT_START_DOLLARS ?? LIVE_STOCK_POLICY_DEFAULTS.trailingProfitStartDollars) || LIVE_STOCK_POLICY_DEFAULTS.trailingProfitStartDollars),
    trailingProfitGivebackDollars: Math.max(0.01, Number(env.TRAILING_PROFIT_GIVEBACK_DOLLARS ?? LIVE_STOCK_POLICY_DEFAULTS.trailingProfitGivebackDollars) || LIVE_STOCK_POLICY_DEFAULTS.trailingProfitGivebackDollars),
    stalePositionExitEnabled: parseBool(env.STOCK_SCANNER_STALE_POSITION_EXIT_ENABLED, LIVE_STOCK_POLICY_DEFAULTS.stalePositionExitEnabled),
    stalePositionMaxHoldMinutes: Math.max(1, safeNumber(env.STOCK_SCANNER_STALE_POSITION_MAX_HOLD_MINUTES, LIVE_STOCK_POLICY_DEFAULTS.stalePositionMaxHoldMinutes)),
    stalePositionMinPeakProfitDollars: Math.max(0, safeNumber(env.STOCK_SCANNER_STALE_POSITION_MIN_PEAK_PROFIT_DOLLARS, LIVE_STOCK_POLICY_DEFAULTS.stalePositionMinPeakProfitDollars)),
    stalePositionMaxExitPnlDollars: safeNumber(env.STOCK_SCANNER_STALE_POSITION_MAX_EXIT_PNL_DOLLARS, LIVE_STOCK_POLICY_DEFAULTS.stalePositionMaxExitPnlDollars),
    stalledWinnerExitEnabled: parseBool(env.STOCK_SCANNER_STALLED_WINNER_EXIT_ENABLED, LIVE_STOCK_POLICY_DEFAULTS.stalledWinnerExitEnabled),
    stalledWinnerMaxHoldMinutes: Math.max(1, safeNumber(env.STOCK_SCANNER_STALLED_WINNER_MAX_HOLD_MINUTES, LIVE_STOCK_POLICY_DEFAULTS.stalledWinnerMaxHoldMinutes)),
    stalledWinnerMaxMinutesSincePeak: Math.max(1, safeNumber(env.STOCK_SCANNER_STALLED_WINNER_MAX_MINUTES_SINCE_PEAK, LIVE_STOCK_POLICY_DEFAULTS.stalledWinnerMaxMinutesSincePeak)),
    stalledWinnerMinProfitDollars: Math.max(0, safeNumber(env.STOCK_SCANNER_STALLED_WINNER_MIN_PROFIT_DOLLARS, LIVE_STOCK_POLICY_DEFAULTS.stalledWinnerMinProfitDollars)),
    sellNetProfitFloorDollars: Math.max(0, safeNumber(env.SELL_NET_PROFIT_FLOOR_DOLLARS, LIVE_STOCK_POLICY_DEFAULTS.sellNetProfitFloorDollars)),
    requireMultiSourceConfirmation: Boolean(env.TWELVE_DATA_API_KEY || env.TWELVEDATA_API_KEY),
    singleSourceMomentumEnabled: parseBool(env.STOCK_SCANNER_SINGLE_SOURCE_MOMENTUM_ENABLED, false),
    singleSourceMomentumMinRankScore: Math.max(0, safeNumber(env.STOCK_SCANNER_SINGLE_SOURCE_MOMENTUM_MIN_RANK_SCORE, 500)),
    minMovePct: Math.max(0, safeNumber(env.STOCK_SCANNER_MIN_MOVE_PCT, stricterLiveEntryDefaults ? LIVE_STOCK_POLICY_DEFAULTS.minMovePct : 0)),
    requireRecentMomentum: parseBool(env.STOCK_SCANNER_REQUIRE_RECENT_MOMENTUM, stricterLiveEntryDefaults),
    minRecentMovePct: Math.max(0, safeNumber(env.STOCK_SCANNER_MIN_RECENT_MOVE_PCT, stricterLiveEntryDefaults ? LIVE_STOCK_POLICY_DEFAULTS.minRecentMovePct : 0.03)),
    minRecentRangePct: Math.max(0, safeNumber(env.STOCK_SCANNER_MIN_RECENT_RANGE_PCT, stricterLiveEntryDefaults ? LIVE_STOCK_POLICY_DEFAULTS.minRecentRangePct : 0.05)),
    minRecentCloseLocationPct: Math.max(0, Math.min(100, safeNumber(env.STOCK_SCANNER_MIN_RECENT_CLOSE_LOCATION_PCT, stricterLiveEntryDefaults ? LIVE_STOCK_POLICY_DEFAULTS.minRecentCloseLocationPct : 60))),
    allowContrarianEntries: parseBool(env.STOCK_SCANNER_ALLOW_CONTRARIAN_ENTRIES, !stricterLiveEntryDefaults),
    blockBuys: parseBool(env.BLOCK_BUYS, false),
    sellMaxPriceDiffPct: safeNumber(env.SELL_MAX_PROVIDER_PRICE_DIFF_PCT, 0.75),
    recentTradePenaltyMinutes: Math.max(0, safeNumber(env.STOCK_SCANNER_RECENT_TRADE_PENALTY_MINUTES, 15)),
    recentTradeRankPenalty: Math.max(0, safeNumber(env.STOCK_SCANNER_RECENT_TRADE_RANK_PENALTY, 20)),
    recentLossPenaltyMinutes: Math.max(0, safeNumber(env.STOCK_SCANNER_RECENT_LOSS_PENALTY_MINUTES, 10)),
    recentLossRankPenalty: Math.max(0, safeNumber(env.STOCK_SCANNER_RECENT_LOSS_RANK_PENALTY, 60)),
    recentStaleExitPenaltyMinutes: Math.max(0, safeNumber(env.STOCK_SCANNER_RECENT_STALE_EXIT_PENALTY_MINUTES, 20)),
    recentStaleExitRankPenalty: Math.max(0, safeNumber(env.STOCK_SCANNER_RECENT_STALE_EXIT_RANK_PENALTY, 40)),
    recentStopExitPenaltyMinutes: Math.max(0, safeNumber(env.STOCK_SCANNER_RECENT_STOP_EXIT_PENALTY_MINUTES, 30)),
    recentStopExitRankPenalty: Math.max(0, safeNumber(env.STOCK_SCANNER_RECENT_STOP_EXIT_RANK_PENALTY, 80)),
    antiChurnEnabled: parseBool(env.ANTI_CHURN_ENABLED, true),
    antiChurnRetentionHours: Math.max(1, safeNumber(env.ANTI_CHURN_RETENTION_HOURS, 24)),
    antiChurnCleanWinCooldownSeconds: Math.max(0, safeNumber(env.ANTI_CHURN_CLEAN_WIN_COOLDOWN_SECONDS, 0)),
    antiChurnTrailingWinCooldownSeconds: Math.max(0, safeNumber(env.ANTI_CHURN_TRAILING_WIN_COOLDOWN_SECONDS, 5 * 60)),
    antiChurnSmallWinCooldownSeconds: Math.max(0, safeNumber(env.ANTI_CHURN_SMALL_WIN_COOLDOWN_SECONDS, 5 * 60)),
    antiChurnGoodLossCooldownSeconds: Math.max(0, safeNumber(env.ANTI_CHURN_GOOD_LOSS_COOLDOWN_SECONDS, 15 * 60)),
    antiChurnBadLossCooldownSeconds: Math.max(0, safeNumber(env.ANTI_CHURN_BAD_LOSS_COOLDOWN_SECONDS, 30 * 60)),
    antiChurnHardStopoutCooldownSeconds: Math.max(0, safeNumber(env.ANTI_CHURN_HARD_STOPOUT_COOLDOWN_SECONDS, 45 * 60)),
    antiChurnRepeatedStopoutMultiplier: Math.max(1, safeNumber(env.ANTI_CHURN_REPEATED_STOPOUT_MULTIPLIER, 2)),
    antiChurnMaxCooldownSeconds: Math.max(0, safeNumber(env.ANTI_CHURN_MAX_COOLDOWN_SECONDS, 90 * 60)),
    antiChurnRecentWinnerProtectionEnabled: parseBool(env.RECENT_WINNER_PROTECTION_ENABLED, true),
    antiChurnRecentWinnerWindowSeconds: Math.max(1, safeNumber(env.ANTI_CHURN_RECENT_WINNER_WINDOW_SECONDS, 30 * 60)),
    antiChurnTinyExitDollars: Math.max(0, safeNumber(env.ANTI_CHURN_TINY_EXIT_DOLLARS, 0.5)),
    antiChurnRapidRoundTripSeconds: Math.max(1, safeNumber(env.ANTI_CHURN_RAPID_ROUND_TRIP_SECONDS, 10 * 60)),
    antiChurnWindowSeconds: Math.max(1, safeNumber(env.ANTI_CHURN_WINDOW_SECONDS, 60 * 60)),
    antiChurnGuardScoreThreshold: Math.max(1, safeNumber(env.ANTI_CHURN_GUARD_SCORE_THRESHOLD, 60)),
    antiChurnGuardTradeCount: Math.max(0, safeNumber(env.ANTI_CHURN_GUARD_TRADE_COUNT, 4)),
    antiChurnGuardStopoutCount: Math.max(0, safeNumber(env.ANTI_CHURN_GUARD_STOPOUT_COUNT, 2)),
    antiChurnGuardTinyExitCount: Math.max(0, safeNumber(env.ANTI_CHURN_GUARD_TINY_EXIT_COUNT, 2)),
    antiChurnGuardRoundTripCount: Math.max(0, safeNumber(env.ANTI_CHURN_GUARD_ROUND_TRIP_COUNT, 2)),
    antiChurnGuardSymbolLoopCount: Math.max(0, safeNumber(env.ANTI_CHURN_GUARD_SYMBOL_LOOP_COUNT, 3)),
    antiChurnGuardSetupLoopCount: Math.max(0, safeNumber(env.ANTI_CHURN_GUARD_SETUP_LOOP_COUNT, 3)),
    setupFatigueEnabled: parseBool(env.SETUP_FATIGUE_ENABLED, true),
    setupFatigueThreshold: Math.max(0, safeNumber(env.SETUP_FATIGUE_THRESHOLD, 60)),
    setupFatigueDecayPerHour: Math.max(0, safeNumber(env.SETUP_FATIGUE_DECAY_PER_HOUR, 8)),
    setupFatigueStopoutPoints: Math.max(0, safeNumber(env.SETUP_FATIGUE_STOPOUT_POINTS, 28)),
    setupFatigueBadLossPoints: Math.max(0, safeNumber(env.SETUP_FATIGUE_BAD_LOSS_POINTS, 16)),
    setupFatigueGoodLossPoints: Math.max(0, safeNumber(env.SETUP_FATIGUE_GOOD_LOSS_POINTS, 6)),
    setupFatigueCleanWinRecoveryPoints: Math.max(0, safeNumber(env.SETUP_FATIGUE_CLEAN_WIN_RECOVERY_POINTS, 10)),
    setupFatiguePauseSeconds: Math.max(0, safeNumber(env.SETUP_FATIGUE_PAUSE_SECONDS, 15 * 60)),
    setupFatigueMaxPauseSeconds: Math.max(0, safeNumber(env.SETUP_FATIGUE_MAX_PAUSE_SECONDS, 90 * 60)),
    sessionGuardsEnabled: parseBool(env.SESSION_GUARDS_ENABLED, false),
    stopoutClusterBlockMinutes: Math.max(0, safeNumber(env.STOCK_SCANNER_STOPOUT_CLUSTER_BLOCK_MINUTES, 30)),
    stopoutClusterBlockCount: Math.max(0, Math.floor(safeNumber(env.STOCK_SCANNER_STOPOUT_CLUSTER_BLOCK_COUNT, 2))),
    maxBuyRiskScore: Math.max(0, safeNumber(env.STOCK_SCANNER_MAX_BUY_RISK_SCORE, 70)),
    spreadRankPenaltyThresholdPct: Math.max(0, safeNumber(env.STOCK_SCANNER_SPREAD_RANK_PENALTY_THRESHOLD_PCT, 0.75)),
    spreadRankPenaltyPerPct: Math.max(0, safeNumber(env.STOCK_SCANNER_SPREAD_RANK_PENALTY_PER_PCT, 25)),
    spreadRankPenaltyCap: Math.max(0, safeNumber(env.STOCK_SCANNER_SPREAD_RANK_PENALTY_CAP, 80)),
    minAdjustedRankScore: safeNumber(env.STOCK_SCANNER_MIN_ADJUSTED_RANK_SCORE, Number.NEGATIVE_INFINITY),
    keepAlive: true,
    runtimeStateEnabled: parseBool(env.SCANNER_RUNTIME_STATE_ENABLED, false),
    requireMarketOpen: parseBool(env.STOCK_SCANNER_REQUIRE_MARKET_OPEN, true),
    openingNoiseMinutes: Math.max(0, safeNumber(env.STOCK_SCANNER_OPENING_NOISE_MINUTES, 5)),
    nearCloseManageOnlyMinutes: Math.max(0, safeNumber(env.STOCK_SCANNER_NEAR_CLOSE_MANAGE_ONLY_MINUTES, 15)),
    volatilityStopEnabled: parseBool(env.STOCK_SCANNER_VOLATILITY_STOP_ENABLED, false),
    marketQualityRankingEnabled: parseBool(env.STOCK_SCANNER_MARKET_QUALITY_RANKING_ENABLED, false),
    executionQualityFeedbackEnabled: parseBool(env.EXECUTION_QUALITY_FEEDBACK_ENABLED, false),
    executionQualityRankPenaltyEnabled: parseBool(env.EXECUTION_QUALITY_RANK_PENALTY_ENABLED, false),
    executionQualitySizeMultiplierEnabled: parseBool(env.EXECUTION_QUALITY_SIZE_MULTIPLIER_ENABLED, false),
    executionQualityCooldownEnabled: parseBool(env.EXECUTION_QUALITY_COOLDOWN_ENABLED, false),
    maxExecutionQualityRankPenalty: Math.max(0, safeNumber(env.MAX_EXECUTION_QUALITY_RANK_PENALTY, 40)),
    minExecutionQualitySizeMultiplier: Math.max(0.5, Math.min(1, safeNumber(env.MIN_EXECUTION_QUALITY_SIZE_MULTIPLIER, 0.5))),
    highSlippageThresholdPct: Math.max(0, safeNumber(env.HIGH_SLIPPAGE_THRESHOLD_PCT, 0.5)),
    badFillThresholdPct: Math.max(0, safeNumber(env.BAD_FILL_THRESHOLD_PCT, 2)),
    executionQualityDecayPerHour: Math.max(0, safeNumber(env.EXECUTION_QUALITY_DECAY_PER_HOUR, 0)),
    riskBudgetSizingEnabled: parseBool(env.RISK_BUDGET_SIZING_ENABLED, false),
    positionSizingMode: String(env.POSITION_SIZING_MODE || (parseBool(env.RISK_BUDGET_SIZING_ENABLED, false) ? 'risk_budget' : 'fixed_notional')).trim().toLowerCase(),
    maxBuyingPowerDeploymentPct: Math.max(0, Math.min(100, safeNumber(env.MAX_BUYING_POWER_DEPLOYMENT_PCT, 100))),
    buyingPowerMarketOrderBufferPct: Math.max(0, Math.min(50, safeNumber(env.BUYING_POWER_MARKET_ORDER_BUFFER_PCT, 0))),
    buyingPowerCashReserve: Math.max(0, safeNumber(env.BUYING_POWER_CASH_RESERVE, safeNumber(env.CASH_RESERVE_DOLLARS, 0))),
    allowBuyingPowerFractionalShares: parseBool(env.ALLOW_BUYING_POWER_FRACTIONAL_SHARES, false),
    maxRiskPerTradeDollars: Math.max(0, safeNumber(env.MAX_RISK_PER_TRADE_DOLLARS, 0)),
    maxRiskPerTradePctEquity: Math.max(0, safeNumber(env.MAX_RISK_PER_TRADE_PCT_EQUITY, 0)),
    maxTradeNotional: Math.max(0, safeNumber(env.MAX_TRADE_NOTIONAL, 0)),
    minStopDistanceDollars: Math.max(0.01, safeNumber(env.MIN_STOP_DISTANCE_DOLLARS, 0.01)),
    maxStopDistanceDollars: Math.max(0, safeNumber(env.MAX_STOP_DISTANCE_DOLLARS, 0)),
    allowRiskBudgetFractionalShares: parseBool(env.ALLOW_RISK_BUDGET_FRACTIONAL_SHARES, false),
    riskBudgetRequireBrokerEquity: parseBool(env.RISK_BUDGET_REQUIRE_BROKER_EQUITY, true),
    candidateLifecycleEnabled: parseBool(env.CANDIDATE_QUEUE_ENABLED, false),
    candidateMinScansBeforeEntry: Math.max(1, Math.floor(safeNumber(env.CANDIDATE_MIN_SCANS_BEFORE_ENTRY, 2))),
    candidateMinSecondsBeforeEntry: Math.max(0, Math.floor(safeNumber(env.CANDIDATE_MIN_SECONDS_BEFORE_ENTRY, 30))),
    candidateMaxAgeSeconds: Math.max(1, Math.floor(safeNumber(env.CANDIDATE_MAX_AGE_SECONDS, 10 * 60))),
    candidateConfirmationRequired: parseBool(env.CANDIDATE_CONFIRMATION_REQUIRED, true),
    candidateQueueMaxSize: Math.max(1, Math.floor(safeNumber(env.CANDIDATE_QUEUE_MAX_SIZE, 12))),
    rankConfidenceDecayEnabled: parseBool(env.RANK_CONFIDENCE_DECAY_ENABLED, false),
    rankConfidenceHalfLifeSeconds: Math.max(1, Math.floor(safeNumber(env.RANK_CONFIDENCE_HALF_LIFE_SECONDS, 15 * 60))),
    rankConfidenceMaxStaleSeconds: Math.max(1, Math.floor(safeNumber(env.RANK_CONFIDENCE_MAX_STALE_SECONDS, 30 * 60))),
    huntToMonitorLatchEnabled: parseBool(env.HUNT_TO_MONITOR_LATCH_ENABLED, false),
    monitorModeAllowsNewBuys: parseBool(env.MONITOR_MODE_ALLOWS_NEW_BUYS, false),
    manageOnlyBlocksBuys: parseBool(env.MANAGE_ONLY_BLOCKS_BUYS, true),
    microRotationGuardEnabled: parseBool(env.MICRO_ROTATION_GUARD_ENABLED, false),
    rotationSoftBandPoints: Math.max(0, safeNumber(env.ROTATION_SOFT_BAND_POINTS, 4)),
    rotationHardBandPoints: Math.max(0, safeNumber(env.ROTATION_HARD_BAND_POINTS, 12)),
    rotationMinHoldScans: Math.max(0, Math.floor(safeNumber(env.ROTATION_MIN_HOLD_SCANS, 1))),
    hotSlotRotationEnabled: parseBool(env.MEME_HOT_SLOT_ROTATION_ENABLED, false),
    hotSlotRotationMinHeatScore: Math.max(0, safeNumber(env.MEME_HOT_SLOT_ROTATION_MIN_HEAT_SCORE, 90)),
    hotSlotRotationMinMarketScore: Math.max(0, safeNumber(env.MEME_HOT_SLOT_ROTATION_MIN_MARKET_SCORE, 75)),
    rotationRequireBreakevenOrBetter: parseBool(env.MEME_ROTATION_REQUIRE_BREAKEVEN_OR_BETTER, true),
    rotationAllowTinyLoss: parseBool(env.MEME_ROTATION_ALLOW_TINY_LOSS, false),
    rotationMaxAllowedLossDollars: Math.max(0, safeNumber(env.MEME_ROTATION_MAX_ALLOWED_LOSS_DOLLARS, 0)),
    rotationProtectStrongRunners: parseBool(env.MEME_ROTATION_PROTECT_STRONG_RUNNERS, true),
    rotationRecheckAfterExit: parseBool(env.MEME_ROTATION_RECHECK_AFTER_EXIT, true),
    rotationExitTimeoutSeconds: Math.max(1, Math.floor(safeNumber(env.MEME_ROTATION_EXIT_TIMEOUT_SECONDS, 30))),
    rotationEntryRecheckMaxAgeSeconds: Math.max(1, Math.floor(safeNumber(env.MEME_ROTATION_ENTRY_RECHECK_MAX_AGE_SECONDS, 30))),
    scannerSymbolSource: String(env.SCANNER_SYMBOL_SOURCE || 'dynamic').trim().toLowerCase(),
  };
}

function trimTrailingSlash(value) {
  return String(value || '').replace(/\/+$/, '');
}

module.exports = {
  SCANNER_CONFIG_KEYS,
  buildScannerConfig,
};
